### ISSUE TITLE
PC初心者に易しい仕様にしよう案

### ISSUE THREAD

**Issue by sata0204** [c01o/beithell#31]
* [ ] 内部的な変数名の隠蔽。(○○を○○にしますか？は避け、○○でよろしいですか？などの質問にする)
* [ ] パス→ファイル、ディレクトリ等windows用語に言い換え
* [ ] 普通の人にとって要らない変数設定も消す(template-pathなど)
* [ ] 大学・学部名の日本語入力は「大学」「学部」を含めないことを明示する。

**Comment by c01o** [comment]
>普通の人にとって～
定義不明瞭。
あと設定を消すのはクソなので、とくに気にしない人は初期値を変更せずそのまま使えるようにはするが
変えたい人がドキュメントを調べれば設定関数を自前で叩ける仕組みは残す方針。
