### ISSUE TITLE
hcsm-setupのバグ

### ISSUE THREAD

**Issue by sata0204** [c01o/beithell#33]
hcsm-write-defvarが正しく動作しない。
新しく関数を生成しない。

**Comment by sata0204** [comment]
setupを使ってもhcsm-var-settingsに(defvar hcsm-TEX-Genkou …)が追加されない。

**Comment by c01o** [comment]
今回の問題はhcsm-get-TEX-Genkou-pathで使ってた変数がローカルじゃなかったせいでboundpが常にtrueだったこと。
以下サンプルコード
```elisp
(defun hoge()
    (progn
        (makunbound `piyo)
        (fuga)
        piyo))

(defun fuga()
    (setq piyo "piyopiyo"))

(hoge) ;; => "piyopiyo" 
```
