### ISSUE TITLE
会社からの要望

### ISSUE THREAD

**Issue by sata0204** [c01o/beithell#47]
内容をコピペしとく。バグもあれば要望もある。Masterが旧版だったっぽいね。

・大学名をローマ字12文字以内で入力
→大学名を対応表に記載されている通りの英語で入力
・大学略称をローマ字で入力
→大学略称を対応表に記載されている通り、大文字アルファベットで入力
・大学名を日本語で入力
→大学名を対応表に記載されている通りの日本語で入力
・出典に記載する大学名を対応表に記載されている通りの日本語で入力
という質問を追加してください。\syutten部分はそれが反映されるようにしてください。
・学部名をローマ字で入力
→学部名を対応表に記載されている通り、アルファベットで入力
・matomeフォルダの学部名.texファイル
一行目がなぜか
\日本大学{日本大学mei大学・商学部}
となりました。
正しくは、
\daigaku{日本大学・商学部}
だと思います。
・
・\syutten[year,日本大学mei大-商]
前述の通り、出典に記載する大学名を反映するようにしてください。
また、15ではなくyearと表示されますので、15と表示されるようにしてください。
・大問ごとのkakunin.texと全体のkakunin.texで、
\input{year-NH-sho}
となっていますので、
\input{15-NH-sho}
となるようにしてください。

**Comment by c01o** [comment]
#48 で大体そっちで解決した？

**Comment by sata0204** [comment]
とりあえず上で挙がってるのは解決した。
