### ISSUE TITLE
\begin{reidai},\end{reidai}が消えるバグ

### ISSUE THREAD

**Issue by sata0204** [c01o/beithell#56]
小問集合が2つ以上あったとき、\begin{reidai},\end{reidai}が生成されないバグが生じる。

**Comment by c01o** [comment]
手元で試した限りでは再現せず。発生時の入力例求む

**Comment by sata0204** [comment]
大問1,2が小問集合問題だった場合、matomeのtexが大問1しか\begin{reidai},\end{reidai}で囲まれておらず、大問2は囲まれていない。
すべての小問集合について、最初の大問しか囲まれない。小問集合が2つあればどんな場合でも再現可能だと思われる。

**Comment by sata0204** [comment]
add-to-listはリスト内に同じ要素があると追加されない。そのため
(add-to-list 'toi-text-lists "\\\\begin{reidai}")
で2回以上追加されなかった。
(setq toi-text-lists (cons "\\\\begin{reidai}" toi-text-lists))
に修正したら正しく動作。会社に提出済み。

**Comment by c01o** [comment]
そのコードだいぶ古いやつや…
HEAD（ 3a0a8f9 ）では再現しないはず。したら報告して
